environment:		
  nodejs_version: "6"

artifacts:
  - path: jsreport.zip

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    

install:  
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version  
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - appveyor-retry npm install
  - "node node_modules/jsreport --init"    

test_script:  
  - node --version
  - npm --version    
  - npm test

before_deploy:  
  - "node_modules/.bin/jsreport-compile.cmd"
  - "7z a jsreport.zip jsreport.exe"
  - "appveyor PushArtifact jsreport.zip"

deploy:  
 provider: GitHub
 auth_token:
  secure: f5JMTlhWW7SKTeONrfO9hweB+AP2EY5VGAdzcM56VRNjIcY4zX7TiC7VWXrn5Dfj
 artifact: /.*\.zip/
 draft: false
 prerelease: false
 force_update: true
 on:
   appveyor_repo_tag: true

build: off
