environment:		
  nodejs_version: "6"

artifacts:
  - path: jsreport.exe
    name: jsreport-win64.zip
    type: zip

install:  
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version  
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - appveyor-retry npm install
  - "node node_modules/jsreport --init"    

test_script:  
  - node --version
  - npm --version    
  - npm test

before_deploy:  
  - "node_modules/.bin/jsreport-compile.cmd"

deploy:  
 provider: GitHub
 auth_token:
  secure: kRsCQ89yBpjEV0w7W8DJ33VW/YhW7U1w/j6g/CEEU03PfarXzPyVcV0WKcXXUzbtgKNCUzx4Hfeio0RAqzf4fYPpJqMh/MOjvoItcP4I1lKyncj+Pa2Zhaa2r8IZ98/PkvFuMR7JFjecwsEfKjjgqAkb5ledvJlcZPWGq/KmEvTAmXxuS4hqHPLrNNXy0cx+QuZLrfOq1YU9U++RwHs2R42Jf9ia6oyHKifZNE+BbDc+DjQ/9dq5GtpfjKUvCMPj4aNRlrWQBfQjqLTnyqKWHzaTLMR4BJFvVXQ3iLeHnNZZEZCAapKCGMcKzCqFbhSj+wM1eb5or+I8cnFttbn1TzYfc+yHEaiPrLqWy1/nDgel9A+lvkQaEAlJEKLTo4TeuFDHATr3N1MT4QBRqNQLpKmX5pjgbgv5+nyOd7ngLtCWzT/X6XIwz88SnRVmKeAvoxQRiSFfz7idC6/yUMJH7a1Wyq5YbMRSUaszK6s0059vbfjAYVl3DBbiyotUNXaHtmjyT04V/DPAPbz2yN4dWLw0yVAzfaLFCmxoXPg81erK0+zat2obDPEjAAwNI/oztZQRwkGfqKmWa9ohDgwebfMYubcGT+XiP8ih0T6j74kpPQJ/PBc6h+tkpO/oXszYiB0YJfVECzkaV+1NFRvo5shvAVOWTSik9yEyhBP3Mn0=
 artifact: jsreport.exe
 draft: false
 prerelease: false
 on:
   appveyor_repo_tag: true

build: off
