matrix:
  - os: linux
  - os: osx
    on:
      tags: true

language: node_js

node_js:
  - '6'
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TlV2eBd3M16e1LmsBR+8H982L1z2Hn5LghbgpwkIvxxBfjo7uuMYSwoL0ihY36Q7nGMYWvCUNn3tPZCeGolXQOdKbwOggjDMpk23rKpTj7D5IL/84Izcz0iQpugi0CZe4OcmoitLIa9h/2x9oGUJAbdmqQawGdHkuASa25tb+h4=
  file:
    - index.js
    - index.js
  on:
    tags: true
