sudo: required
dist: trusty
language: node_js

node_js:
- '6'

before_deploy: 
  - "node node_modules/jsreport --init"
  - "node_modules/.bin/jsreport-compile"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6

deploy:
  provider: releases
  api_key:
    secure: kRsCQ89yBpjEV0w7W8DJ33VW/YhW7U1w/j6g/CEEU03PfarXzPyVcV0WKcXXUzbtgKNCUzx4Hfeio0RAqzf4fYPpJqMh/MOjvoItcP4I1lKyncj+Pa2Zhaa2r8IZ98/PkvFuMR7JFjecwsEfKjjgqAkb5ledvJlcZPWGq/KmEvTAmXxuS4hqHPLrNNXy0cx+QuZLrfOq1YU9U++RwHs2R42Jf9ia6oyHKifZNE+BbDc+DjQ/9dq5GtpfjKUvCMPj4aNRlrWQBfQjqLTnyqKWHzaTLMR4BJFvVXQ3iLeHnNZZEZCAapKCGMcKzCqFbhSj+wM1eb5or+I8cnFttbn1TzYfc+yHEaiPrLqWy1/nDgel9A+lvkQaEAlJEKLTo4TeuFDHATr3N1MT4QBRqNQLpKmX5pjgbgv5+nyOd7ngLtCWzT/X6XIwz88SnRVmKeAvoxQRiSFfz7idC6/yUMJH7a1Wyq5YbMRSUaszK6s0059vbfjAYVl3DBbiyotUNXaHtmjyT04V/DPAPbz2yN4dWLw0yVAzfaLFCmxoXPg81erK0+zat2obDPEjAAwNI/oztZQRwkGfqKmWa9ohDgwebfMYubcGT+XiP8ih0T6j74kpPQJ/PBc6h+tkpO/oXszYiB0YJfVECzkaV+1NFRvo5shvAVOWTSik9yEyhBP3Mn0=
  file: jsreport.exe
  on:
    repo: pofider/test
