os:
  - linux
  - osx     

if: env($TRAVIS_OS_NAME)=linux

sudo: required
language: node_js
node_js:
- '4'
- '6'

deploy:
  provider: releases
  api_key:
    secure: jIunU1uzb+hnsERXASIeMnFGXoesziBHa8eUQZDZoU5ohlTu+KCf42YPmKuT+qxjWoRbfXmVB0Pyd4XOWa/3xDsdGMjHdf+EZLndi+LJsL3W0ofTirMzE9/XYGx71YOJZVMvSiBDnhIVTXFEg797RBMoXU1T+8sltg2NLF53deM0ncOli4RHbqxDP69bNZ6xR4Vzp+GT/OBLC7J+0o/sULaEHuHzMi3yrq43KVrUbUmghVE4d+h7N2xlvFRfP0hknKcip945Wmxbnc+QlD/gSqoSSyzhAvit7xD4N8r5mO/IjwA3qfM1OJNoalWsYrBlsvxiPHWCsIihDjoqX0wYiYT7QoLNNZaMIPDQBbymYp21bPXshhUSh/2FpPbPpqOX3L89TYvXGdJOP5d9P06c3J7xfZvjyJrkz0QfXhs+zRXemTnXL4HiqnfV/2S/exxKgcTf75zaPbmldnhYEJfXU4MbBv44HkZpvsSUvprDhp5Kzx8T3ec60modMTFsHkFmv+VqKID7+tXzJANze9bl4KomOrAxsD3RaFiA+oWxOzuWyWwxWAvAr2cWurEvO12nWJroZEBOg0BjgZXnt/AJ1OLeu+99tii4uMLF0FH3giXEaCOU4aUjHYYglwbICWPVm9CyH3eqrGiN9cqECdsfqKwopj4Nje4fGj3ATbp7JL4=
  file: package.json
  on:
    tags: true
