name: docker-windows 

on:
  release:
    types: [published]

jobs:
  push:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2    

      - run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -f packages/jsreport/docker/windowsservercore/Dockerfile -t $env:TAG .
          docker push $env:TAG
          docker logout
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_PASSWORD }}
          TAG: pofider/test:${{ github.event.release.tag_name }}-windowsservercore    