name: docker-full 

on:
  release:
    types: [published]

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2    

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push default
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: packages/jsreport/docker/full/Dockerfile
          tags: jsreport/jsreport:${{ github.event.release.tag_name }}-full, jsreport/jsreport:latest-full