name: docker-windows 

on:
  release:
    types: [published]

jobs:
  push:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2    

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: pofider/test
          tags: ${{ github.event.release.tag_name }}-windowsservercore, latest-windowsservercore
          registry: https://hub.docker.com/
          dockerfile: packages/jsreport/docker/windowsservercore/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     