name: docker-full 

on:
  release:
    types: [published]

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2     

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push default
        uses: docker/build-push-action@v2
        with:
          push: true
          file: packages/jsreport/full/Dockerfile
          tags: pofider/test:${{ github.event.release.tag_name }}-full, pofider/test:latest-full