name: linux-binary 

on:
  release:
    types: [published]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2     

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - run: yarn install

      - run: yarn compile

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jsreport-linux.tar.gz
